# Site settings
title: Coffee and Code
header-img: img/home-bg.png
email: aine3d@gmail.com
copyright_name: ainevethe
description: > # this means to ignore newlines until "baseurl:"
  mid-life career changer takes on code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SofiaCelen
github_username:  ainevethe
learn_profile: ainevethe
email_username: aine3d@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
